/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e84ecb9d-260f-48dc-9f71-6f0ed227ee1b",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_U8kh17XjU",
    "aws_user_pools_web_client_id": "78qm31g0nn90lcucf3tu6btkhh",
    "oauth": {
        "domain": "fluxroom32d97741-32d97741-dev.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "fluxroom://",
        "redirectSignOut": "fluxroom://",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS"
};


export default awsmobile;
