GET https://fluxroom-backend-beta.herokuapp.com/user/5f386554eed5170017ecb3ff

###
GET https://fluxroom-backend-beta.herokuapp.com/allusers

###
GET https://fluxroom-backend-beta.herokuapp.com/getbyphone?phone=+918433802669

 