import constants from "./constants";
export default {
  gradient: ["#4640C1", "#6E34A1"],
  input: {
    alignItems: "center",
    flexDirection: "row",
    width: constants.width * 0.8,
    height: 50,
    borderRadius: 15,
    paddingHorizontal: 10,
    backgroundColor: "#f5f5f5",
    marginVertical: 10,
    borderRadius: 10,
    shadowOffset: { width: 0.1, height: 0.1 },
    shadowColor: "black",
    shadowOpacity: 0.2,
  },
  textInput: {
    flex: 1,
    height: 50,
    paddingLeft: 10,
  },
  error: {
    color: "crimson",
    fontSize: 16,
  },
  button: {
    width: constants.width * 0.8,
    height: 50,
    backgroundColor: constants.primary,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginBottom: 25,
    marginTop: 15,
  },
  touchableButton: {
    width: constants.width * 0.9,
    height: 50,
    backgroundColor: constants.primary,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginVertical: 10,
    shadowOffset: { width: 0.1, height: 0.1 },
    shadowColor: "black",
    shadowOpacity: 0.1,
  },
  lowOpacityTouchableButton: {
    width: constants.width * 0.9,
    height: 50,
    backgroundColor: "rgba(255,255,255,0.1)",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginVertical: 10,
    shadowOffset: { width: 0.1, height: 0.1 },
    shadowColor: "black",
    shadowOpacity: 0.1,
  },
  buttonText: {
    color: "white",
    fontSize: 18,
    letterSpacing: 1,
    fontFamily: "Helvetica",
  },
  rootAppbarHeader: {
    width: constants.width,
    height: constants.height * 0.075,
    backgroundColor: "transparent",
  },
  rootAppbarTitle: {
    color: "white",
    fontSize: 25,
    fontWeight: "200",
    fontFamily: "Helvetica",
  },
};
